#!/usr/bin/env node
/**
 * Bundle the MCP App UI into a single self-contained HTML string.
 *
 * The host renders ui:// resources under a deny-by-default CSP, so a page that
 * pulls a script from anywhere — even a relative path — renders blank. Both the
 * app logic and the ext-apps client have to be inlined into the markup, which
 * is what this produces.
 *
 * Output is a generated TS module rather than a file read at runtime, because
 * mem-port publishes only `bin` and `dist`; a stray .html next to the source
 * would not ship.
 */
import { build } from "esbuild";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const uiDir = path.join(repoRoot, "src", "mcp", "ui");

/**
 * Drop zod's translated error messages — 144 kB of the 301 kB bundle, for 40+
 * languages this page never selects.
 *
 * They survive tree-shaking only because zod re-exports them as a namespace
 * (`export * as locales from "../locales/index.js"`), and a namespace object has
 * to be complete. The English table is a *separate* direct import and is not
 * touched by this, so validation errors still read normally; the stub only
 * empties `z.locales`, which nothing on this page calls.
 */
const dropZodLocales = {
  name: "drop-zod-locales",
  setup(build) {
    // The filter sees the import specifier as written ("../locales/index.js"),
    // so the importer is what identifies it as zod's.
    build.onResolve({ filter: /locales[\\/]index\.js$/ }, (args) =>
      args.importer.includes(`${path.sep}zod${path.sep}`) ? { path: "zod-locales-stub", namespace: "stub" } : undefined
    );
    build.onLoad({ filter: /^zod-locales-stub$/, namespace: "stub" }, () => ({
      contents: "export {};",
      loader: "js",
    }));
  },
};

const bundle = await build({
  entryPoints: [path.join(uiDir, "app.ts")],
  bundle: true,
  format: "iife",
  target: "es2022",
  platform: "browser",
  minify: true,
  write: false,
  logLevel: "warning",
  plugins: [dropZodLocales],
});

const script = bundle.outputFiles[0].text;

// A literal </script> anywhere in the bundle would close the tag early. esbuild
// does not escape for an HTML host, so do it here.
const safeScript = script.replace(/<\/script/gi, "<\\/script");

const html = await fs.readFile(path.join(uiDir, "app.html"), "utf-8");

// The replacement MUST be a function. Passing the bundle as a replacement
// string makes String.replace interpret its `$` patterns: minified zod is full
// of regex end-anchors inside template literals (`^${x}$`), and that trailing
// "$`" means "everything before the match" — which splices a copy of the page
// into its own <script> at every occurrence. It produced a page that still
// looked right structurally (a <script>, no external assets) but whose bundle
// no longer parsed, so the app silently never ran. A function replacement
// disables $-substitution outright.
const withScript = html.replace(
  "</body>",
  () => `  <script type="module">${safeScript}</script>\n  </body>`
);

if (withScript === html) {
  throw new Error("app.html has no </body> to inject the bundle into");
}

const generated = `// Generated by scripts/build-app-ui.mjs — do not edit.
// Source: src/mcp/ui/app.html + src/mcp/ui/app.ts

export const APP_HTML = ${JSON.stringify(withScript)};
`;

await fs.writeFile(path.join(uiDir, "generated.ts"), generated);

const kb = (Buffer.byteLength(withScript) / 1024).toFixed(1);
console.error(`built MCP App UI: ${kb} kB inlined into src/mcp/ui/generated.ts`);
